version: '3.6'

services:
  server:
    container_name: server
    build:
      context: ./services/server
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5000
    volumes:
      - ./services/server:/app
  fake_yandex_storage:
    build:
      context: ./services/emulator
    container_name: fake_yandex_storage
    ports:
      - 5001:8080
